//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTuotteetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilausrivit
    {
        public int TilausriviID { get; set; }
        public int TilausID { get; set; }
        public int TuoteID { get; set; }
        public int Maara { get; set; }
        public decimal Ahinta { get; set; }
    
        public virtual Tilaukset Tilaukset { get; set; }
        public virtual Tuotteet Tuotteet { get; set; }
    }
}
